server:
  servlet:
    context-path: /auth
  port: 3000
spring:
  main:
    banner-mode: off
  application:
    name: AUTH-SERVICE
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: mm_root
    password: mm_root

security:
  security-key: GF4gtN9DLWnglX8BlWXiAGVTwGqv76pnz7KSXWeQirtY4748pUyjkUbAicE0tkNxTbIMOT0M9o9n81R/W/RNpQ==

eureka:
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/