server:
  servlet:
    context-path: /product
  port: 4000
spring:
  main:
    banner-mode: off
  application:
    name: PRODUCT-SERVICE
  cloud:
    config:
      enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: mm_root
    password: mm_root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/