server:
  port: 5000

spring:
  application:
    name: ORDER-SERVICE
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: mm_root
    password: mm_root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/